/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestingIndexRouteImport } from './routes/testing/index'
import { Route as MazeIndexRouteImport } from './routes/maze/index'
import { Route as CoinflipIndexRouteImport } from './routes/coinflip/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingIndexRoute = TestingIndexRouteImport.update({
  id: '/testing/',
  path: '/testing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeIndexRoute = MazeIndexRouteImport.update({
  id: '/maze/',
  path: '/maze/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinflipIndexRoute = CoinflipIndexRouteImport.update({
  id: '/coinflip/',
  path: '/coinflip/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinflip': typeof CoinflipIndexRoute
  '/maze': typeof MazeIndexRoute
  '/testing': typeof TestingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinflip': typeof CoinflipIndexRoute
  '/maze': typeof MazeIndexRoute
  '/testing': typeof TestingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coinflip/': typeof CoinflipIndexRoute
  '/maze/': typeof MazeIndexRoute
  '/testing/': typeof TestingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/coinflip' | '/maze' | '/testing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/coinflip' | '/maze' | '/testing'
  id: '__root__' | '/' | '/about' | '/coinflip/' | '/maze/' | '/testing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoinflipIndexRoute: typeof CoinflipIndexRoute
  MazeIndexRoute: typeof MazeIndexRoute
  TestingIndexRoute: typeof TestingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/': {
      id: '/testing/'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze/': {
      id: '/maze/'
      path: '/maze'
      fullPath: '/maze'
      preLoaderRoute: typeof MazeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coinflip/': {
      id: '/coinflip/'
      path: '/coinflip'
      fullPath: '/coinflip'
      preLoaderRoute: typeof CoinflipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoinflipIndexRoute: CoinflipIndexRoute,
  MazeIndexRoute: MazeIndexRoute,
  TestingIndexRoute: TestingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
